/*
  宏美旅行社網站資料表
  Version: 0515V06
  由 admin-home.html 匯出。
*/
window.HOME_TOURS = [
  {
    "id": "seacow",
    "visible": true,
    "sort": 10,
    "duration": "一日遊",
    "badge": "一日遊",
    "groupSize": "4人成團",
    "extra1": "",
    "extra2": "",
    "image": "tour-seacow.jpg",
    "imagePosition": "center center",
    "name": "唯一之旅・芳苑海牛體驗",
    "desc": "搭乘全台唯一海牛車深入潮間帶，採蚵挖蛤蜊，玻璃媽祖廟、台語文創一次玩足。",
    "weekdayPrice": "NT$2,200",
    "holidayPrice": "NT$2,700",
    "price": "平日 NT$2,200",
    "priceNote": "假日 NT$2,700",
    "link": "tour-seacow.html",
    "featured": false,
    "showTours": true,
    "category": "台灣觀巴",
    "customCategory": ""
  },
  {
    "id": "dragon",
    "visible": true,
    "sort": 20,
    "duration": "一日遊",
    "badge": "一日遊",
    "groupSize": "4人成團",
    "extra1": "台灣觀巴",
    "extra2": "",
    "image": "tour-dragon.jpg",
    "imagePosition": "center center",
    "name": "火車追龍漫漫遊",
    "desc": "山林鐵路吸收芬多精，深入部落認識原住民圖騰，親手體驗烙印特殊木桶餐盒。",
    "weekdayPrice": "NT$2,200",
    "holidayPrice": "NT$2,700",
    "price": "平日 NT$2,200",
    "priceNote": "假日 NT$2,700",
    "link": "tour-dragon.html",
    "featured": false,
    "showTours": true,
    "category": "台灣觀巴",
    "customCategory": ""
  },
  {
    "id": "secret",
    "visible": true,
    "sort": 30,
    "duration": "二日遊",
    "badge": "二日遊",
    "groupSize": "4人成團",
    "extra1": "一泊3食",
    "extra2": "台灣觀巴",
    "image": "tour-secret.jpg",
    "imagePosition": "center center",
    "name": "國家風景區秘境探索二日遊",
    "desc": "太平雲梯、竹坑溪步道、來吉部落 DIY，住宿賴坤陽的家，感受有別以往的阿里山。",
    "weekdayPrice": "NT$5,900",
    "holidayPrice": "NT$6,400",
    "price": "平日 NT$5,900",
    "priceNote": "假日 NT$6,400",
    "link": "tour-secret.html",
    "featured": true,
    "showTours": true,
    "category": "台灣觀巴",
    "customCategory": ""
  },
  {
    "id": "coffee",
    "visible": true,
    "sort": 40,
    "duration": "一日遊",
    "badge": "一日遊",
    "groupSize": "4人成團",
    "extra1": "台灣觀巴",
    "extra2": "",
    "image": "tour-coffee.jpg",
    "imagePosition": "center center",
    "name": "咖香茶薰・八卦山台地深度遊",
    "desc": "彰化南投低海拔咖啡產區體驗，親手製作耳掛咖啡、品嘗茶薰六覺，從產地到生活。",
    "weekdayPrice": "NT$2,200",
    "holidayPrice": "NT$2,700",
    "price": "平日 NT$2,200",
    "priceNote": "假日 NT$2,700",
    "link": "tour-coffee.html",
    "featured": true,
    "showTours": true,
    "category": "台灣觀巴",
    "customCategory": ""
  },
  {
    "id": "grape",
    "visible": true,
    "sort": 50,
    "duration": "一日遊",
    "badge": "一日遊",
    "groupSize": "6人成團",
    "extra1": "含餐",
    "extra2": "",
    "image": "poster-grape.jpg",
    "imagePosition": "center top",
    "name": "彰化微醺花香小旅行",
    "desc": "漫步路葡萄隧道、享受葡萄宴，下午田尾公路花園漫遊，微醺花香一日輕旅行。",
    "weekdayPrice": "NT$2,599",
    "holidayPrice": "",
    "price": "平日 NT$2,599",
    "priceNote": "",
    "link": "tour-grape.html",
    "featured": true,
    "showTours": true,
    "category": "新增路線",
    "customCategory": ""
  },
  {
    "id": "train",
    "visible": true,
    "sort": 60,
    "duration": "三日遊",
    "badge": "三日遊",
    "groupSize": "",
    "extra1": "",
    "extra2": "",
    "image": "poster-train.jpg",
    "imagePosition": "center top",
    "name": "藍皮解憂號・阿塱壹三日遊",
    "desc": "搭乘全台最後非冷氣列車穿越南迴山海，走進阿塱壹古道，聆聽太平洋的原始浪聲。",
    "weekdayPrice": "NT$9,100",
    "holidayPrice": "",
    "price": "平日 NT$9,100",
    "priceNote": "",
    "link": "tour-train.html",
    "featured": true,
    "showTours": true,
    "category": "三日遊",
    "customCategory": ""
  },
  {
    "id": "tour-mp68ywl5-l6ff",
    "visible": true,
    "featured": true,
    "showTours": true,
    "sort": 70,
    "duration": "一日遊",
    "badge": "一日遊",
    "category": "新增路線",
    "customCategory": "",
    "groupSize": "4人成團",
    "extra1": "",
    "extra2": "",
    "image": "poster-turtle.jpg",
    "imagePosition": "center top",
    "name": "龜山島一日遊",
    "desc": "蘭陽博物館・烏石港出海・繞島登島・海上賞鯨豚\n台灣唯一活火山島，遇見太平洋的神秘與壯闊",
    "weekdayPrice": "2600",
    "holidayPrice": "",
    "price": "平日 2600",
    "priceNote": "",
    "link": "tour-turtle.html"
  }
];

window.HOME_NEWS = [
  {
    "id": "passport-permit",
    "visible": true,
    "showHomeNews": true,
    "showNews": true,
    "sort": 10,
    "date": "2026/05/15",
    "category": "服務公告",
    "customCategory": "",
    "title": "本公司可代辦護照及台胞證",
    "summary": "彰化在地服務，可協助護照及台胞證代辦，也可配合夜間收件，歡迎來電或 LINE 洽詢。",
    "link": "#contact"
  },
  {
    "id": "custom-sticker",
    "visible": true,
    "showHomeNews": true,
    "showNews": true,
    "sort": 20,
    "date": "2026/05/15",
    "category": "延伸服務",
    "customCategory": "",
    "title": "企業／品牌客製化 LINE 貼圖服務",
    "summary": "可協助店家、品牌與公司行號製作專屬 LINE 貼圖，適合活動宣傳、客服互動與社群行銷。",
    "link": "#contact"
  },
  {
    "id": "route-guishan",
    "visible": true,
    "showHomeNews": true,
    "showNews": true,
    "sort": 30,
    "date": "2026/05/15",
    "category": "新增路線",
    "customCategory": "",
    "title": "龜山島一日遊開放洽詢",
    "summary": "台中出發，安排蘭陽博物館、烏石港、龜山島繞島、登島與海上賞鯨。",
    "link": "#contact"
  },
  {
    "id": "route-secret",
    "visible": true,
    "showHomeNews": false,
    "showNews": true,
    "sort": 40,
    "date": "2026/05/15",
    "category": "台灣觀巴",
    "customCategory": "",
    "title": "國家風景區秘境探索二日遊",
    "summary": "4人成行、2天1夜、一泊3食，走訪太平雲梯、得恩亞納與奮起湖老街。",
    "link": "tour-secret.html"
  }
];
